/**
 * 19-feature elastic-net (lambda.min), primary PRISM/PELOD midpoint imputation.
 * Coefficients from classifier_coefficients_clove model.csv (normal_imputation_full_run).
 * Regenerate via Clove OG Model Final Boss/export_web_model_params.R
 */
export const MODEL = {
  name: "HYPER-SCREEN",
  version: "1.4.0",
  threshold: 0.7,
  outputLabel: "risk_score",
  intercept: 2.75979731054851,
  // Platt recalibration: fit on derivation in-sample predictions using these
  // exact website coefficients (class weight 5.5). Applied per patient for
  // absolute-probability display only — classification still uses raw score.
  platt: {
    intercept: -1.7418874273,
    slope: 1.2514909806,
    fitSource: "derivation in-sample (CAF-PINT + PALI + REDVENT)",
  },
  derivationCohorts: ["CAFPINT", "PALI", "REDVENT"],
  hyperparameters: {
    alpha: 0.15,
    classWeight: 5.5,
    nfolds: 10,
    seed: 0,
  },
  predictors: [
    {
      id: "pelodwbc",
      label: "White blood cell count",
      group: "PELOD-2",
      type: "continuous",
      unit: "×10³/μL",
      coefficient: -0.0277267440397074,
      imputation: "prism_peleod_mid",
      derivationMedian: 7.5,
      step: 0.1,
      min: 0,
    },
    {
      id: "pelodplate",
      label: "Platelet count",
      group: "PELOD-2",
      type: "continuous",
      unit: "×10³/μL",
      coefficient: -0.00477268249795745,
      imputation: "prism_peleod_mid",
      derivationMedian: 246.5,
      step: 1,
      min: 0,
    },
    {
      id: "pelodpt",
      label: "Prothrombin time",
      group: "PELOD-2",
      type: "continuous",
      unit: "sec",
      coefficient: 0.0530462801101624,
      imputation: "prism_peleod_mid",
      derivationMedian: 16.5,
      step: 0.1,
      min: 0,
    },
    {
      id: "pelodhr",
      label: "Heart rate",
      group: "PELOD-2",
      type: "continuous",
      unit: "bpm",
      coefficient: 0.00417930079582033,
      imputation: "prism_peleod_mid",
      derivationMedian: 144,
      step: 1,
      min: 0,
    },
    {
      id: "pelodlact",
      label: "Lactate",
      group: "PELOD-2",
      type: "continuous",
      unit: "mmol/L",
      coefficient: 0.12217627540685,
      imputation: "prism_peleod_mid",
      derivationMedian: 2.38,
      step: 0.1,
      min: 0,
    },
    {
      id: "prismpao2lo",
      label: "PaO₂/FiO₂ low (PaO₂)",
      group: "PRISM-III",
      type: "continuous",
      unit: "mmHg",
      coefficient: 0.000263046020695817,
      imputation: "prism_peleod_mid",
      derivationMedian: 85,
      step: 0.1,
      min: 0,
    },
    {
      id: "prismbunhi",
      label: "Blood urea nitrogen (high)",
      group: "PRISM-III",
      type: "continuous",
      unit: "mg/dL",
      coefficient: 0.0374691803759535,
      imputation: "prism_peleod_mid",
      derivationMedian: 12,
      step: 0.1,
      min: 0,
    },
    {
      id: "prismph",
      label: "Blood pH",
      group: "PRISM-III",
      type: "continuous",
      unit: "",
      coefficient: -1.31355689548501,
      imputation: "prism_peleod_mid",
      derivationMedian: 7.35,
      step: 0.01,
      min: 6.5,
      max: 8,
    },
    {
      id: "prismk",
      label: "Potassium",
      group: "PRISM-III",
      type: "continuous",
      unit: "mEq/L",
      coefficient: -0.0859683739569753,
      imputation: "prism_peleod_mid",
      derivationMedian: 4.1,
      step: 0.1,
      min: 0,
    },
    {
      id: "prismtemphi",
      label: "Highest body temperature",
      group: "PRISM-III",
      type: "continuous",
      unit: "°C",
      coefficient: 0.162247200359471,
      imputation: "prism_peleod_mid",
      derivationMedian: 38,
      step: 0.1,
      min: 30,
      max: 45,
    },
    {
      id: "wt",
      label: "Weight",
      group: "Demographics & support",
      type: "continuous",
      unit: "kg",
      coefficient: 0.00148174648281102,
      imputation: "derivation_median",
      derivationMedian: 19.5,
      step: 0.1,
      min: 0,
    },
    {
      id: "male",
      label: "Male sex",
      group: "Demographics & support",
      type: "binary",
      coefficient: 0.252843070286431,
      imputation: "prism_peleod_mid",
      derivationMedian: 0,
      yesLabel: "Male",
      noLabel: "Female / other",
    },
    {
      id: "vaso",
      label: "Vasopressor use",
      group: "Demographics & support",
      type: "binary",
      coefficient: 0.306746639859612,
      imputation: "prism_peleod_mid",
      derivationMedian: 0,
      yesLabel: "Yes",
      noLabel: "No",
    },
    {
      id: "prisminpt",
      label: "Inpatient admission",
      group: "PRISM-III",
      type: "binary",
      coefficient: 0.282897566783369,
      imputation: "prism_peleod_mid",
      derivationMedian: 0,
      yesLabel: "Yes",
      noLabel: "No",
    },
    {
      id: "prismpostop",
      label: "Postoperative admission",
      group: "PRISM-III",
      type: "binary",
      coefficient: -0.591087286049256,
      imputation: "prism_peleod_mid",
      derivationMedian: 0,
      yesLabel: "Yes",
      noLabel: "No",
    },
    {
      id: "prismprevadm",
      label: "Previous ICU admission",
      group: "PRISM-III",
      type: "binary",
      coefficient: 0.14484473607244,
      imputation: "prism_peleod_mid",
      derivationMedian: 0,
      yesLabel: "Yes",
      noLabel: "No",
    },
    {
      id: "prismcancer",
      label: "Underlying malignancy",
      group: "PRISM-III",
      type: "binary",
      coefficient: 0.668678465996775,
      imputation: "prism_peleod_mid",
      derivationMedian: 0,
      yesLabel: "Yes",
      noLabel: "No",
    },
    {
      id: "prismnonop",
      label: "Non-operative admission",
      group: "PRISM-III",
      type: "binary",
      coefficient: 0.970357343059964,
      imputation: "prism_peleod_mid",
      derivationMedian: 0,
      yesLabel: "Yes",
      noLabel: "No",
    },
    {
      id: "bicarb",
      label: "Bicarbonate",
      group: "PELOD-2",
      type: "continuous",
      unit: "mEq/L",
      coefficient: -0.0115044168285718,
      imputation: "prism_peleod_mid",
      derivationMedian: 25,
      step: 0.1,
      min: 0,
    },
  ],
};
