/**
 * Paper Table 14 — elastic-net penalized logistic regression (lambda.min)
 * Trained on derivation cohorts (CAFPINT, PALI, REDVENT) using all candidate
 * predictors; these 14 features match the published manuscript coefficient table.
 * Missing values imputed with medians from the combined development dataset.
 */
export const MODEL = {
  name: "HYPER-SCREEN",
  version: "1.1.0",
  threshold: 0.7,
  intercept: 3.675996,
  derivationCohorts: ["CAFPINT", "PALI", "REDVENT"],
  hyperparameters: {
    alpha: 0.15,
    classWeight: 5.5,
    nfolds: 10,
    seed: 0,
  },
  predictors: [
    {
      id: "pelodwbc",
      label: "White blood cell count",
      group: "PELOD-2",
      type: "continuous",
      unit: "×10³/μL",
      coefficient: -0.0229619511715269,
      median: 7.9,
      step: 0.1,
      min: 0,
      placeholder: "7.9",
    },
    {
      id: "pelodplate",
      label: "Platelet count",
      group: "PELOD-2",
      type: "continuous",
      unit: "×10³/μL",
      coefficient: -0.00384223994899715,
      median: 128,
      step: 1,
      min: 0,
      placeholder: "128",
    },
    {
      id: "pelodpt",
      label: "Prothrombin time",
      group: "PELOD-2",
      type: "continuous",
      unit: "sec",
      coefficient: 0.0472601604597479,
      median: 16.1,
      step: 0.1,
      min: 0,
      placeholder: "16.1",
    },
    {
      id: "pelodhr",
      label: "Heart rate",
      group: "PELOD-2",
      type: "continuous",
      unit: "bpm",
      coefficient: 0.00595229263287575,
      median: 148,
      step: 1,
      min: 0,
      placeholder: "148",
    },
    {
      id: "pelodlact",
      label: "Lactate",
      group: "PELOD-2",
      type: "continuous",
      unit: "mmol/L",
      coefficient: 0.113266039194193,
      median: 2,
      step: 0.1,
      min: 0,
      placeholder: "2.0",
    },
    {
      id: "prismbunhi",
      label: "Blood urea nitrogen (high)",
      group: "PRISM-III",
      type: "continuous",
      unit: "mg/dL",
      coefficient: 0.026095121108028,
      median: 13,
      step: 0.1,
      min: 0,
      placeholder: "13",
    },
    {
      id: "prismph",
      label: "Blood pH",
      group: "PRISM-III",
      type: "continuous",
      unit: "",
      coefficient: -1.57326688178857,
      median: 7.32,
      step: 0.01,
      min: 6.5,
      max: 8,
      placeholder: "7.32",
    },
    {
      id: "prismk",
      label: "Potassium abnormality",
      group: "PRISM-III",
      type: "continuous",
      unit: "PRISM score points",
      coefficient: -0.0207702241498202,
      median: 4.1,
      step: 0.1,
      min: 0,
      placeholder: "4.1",
    },
    {
      id: "prismtemphi",
      label: "Highest body temperature",
      group: "PRISM-III",
      type: "continuous",
      unit: "°C",
      coefficient: 0.128108211835843,
      median: 38,
      step: 0.1,
      min: 30,
      max: 45,
      placeholder: "38.0",
    },
    {
      id: "prismgluc",
      label: "Blood glucose",
      group: "PRISM-III",
      type: "continuous",
      unit: "mg/dL",
      coefficient: -0.000848053958869172,
      median: 155,
      step: 1,
      min: 0,
      placeholder: "155",
    },
    {
      id: "intub",
      label: "Mechanical ventilation",
      group: "PRISM-III",
      type: "binary",
      coefficient: 0.537536302197735,
      median: 1,
      yesLabel: "Yes",
      noLabel: "No",
    },
    {
      id: "ageyrs",
      label: "Age",
      group: "Demographics & support",
      type: "continuous",
      unit: "years",
      coefficient: 0.0133783968232915,
      median: 5.2848318463,
      step: 0.1,
      min: 0,
      placeholder: "5.3",
    },
    {
      id: "male",
      label: "Male sex",
      group: "Demographics & support",
      type: "binary",
      coefficient: 0.430799316188825,
      median: 1,
      yesLabel: "Male",
      noLabel: "Female / other",
    },
    {
      id: "vaso",
      label: "Vasopressor use",
      group: "Demographics & support",
      type: "binary",
      coefficient: 0.237185461325348,
      median: 1,
      yesLabel: "Yes",
      noLabel: "No",
    },
  ],
};
