/**
 * Locked 18-predictor elastic-net (lambda.min), primary PRISM/PELOD midpoint imputation.
 * Same model as the manuscript and Tanzania locked analysis (CAF-PINT + PALI + REDvent;
 * alpha 0.15; class weight 5.5). Regenerate via scripts/export_locked18_web_params.R
 */
export const MODEL = {
  name: "HYPER-SCREEN",
  version: "2.0.0",
  threshold: 0.7,
  outputLabel: "risk_score",
  intercept: 3.1099542873,
  derivationCohorts: ["CAFPINT", "PALI", "REDVENT"],
  hyperparameters: {
    alpha: 0.15,
    classWeight: 5.5,
    nfolds: 10,
    seed: 0,
  },
  predictors: [
    {
      id: "prismpao2lo",
      label: "PaO₂/FiO₂ low (PaO₂)",
      group: "PRISM-III",
      type: "continuous",
      unit: "mmHg",
      coefficient: 0.00025787485482,
      imputation: "prism_peleod_mid",
      derivationMedian: 85,
      step: 0.1,
      min: 0,
    },
    {
      id: "prismbunhi",
      label: "Blood urea nitrogen (high)",
      group: "PRISM-III",
      type: "continuous",
      unit: "mg/dL",
      coefficient: 0.0384552635,
      imputation: "prism_peleod_mid",
      derivationMedian: 12,
      step: 0.1,
      min: 0,
    },
    {
      id: "prismph",
      label: "Blood pH",
      group: "PRISM-III",
      type: "continuous",
      unit: "",
      coefficient: -1.3053510437,
      imputation: "prism_peleod_mid",
      derivationMedian: 7.35,
      step: 0.01,
      min: 6.5,
      max: 8,
    },
    {
      id: "prismk",
      label: "Potassium",
      group: "PRISM-III",
      type: "continuous",
      unit: "mEq/L",
      coefficient: -0.082205517004,
      imputation: "prism_peleod_mid",
      derivationMedian: 4.1,
      step: 0.1,
      min: 0,
    },
    {
      id: "prismtemphi",
      label: "Highest body temperature",
      group: "PRISM-III",
      type: "continuous",
      unit: "°C",
      coefficient: 0.15000776251,
      imputation: "prism_peleod_mid",
      derivationMedian: 38,
      step: 0.1,
      min: 30,
      max: 45,
    },
    {
      id: "bicarb",
      label: "Bicarbonate",
      group: "PRISM-III",
      type: "continuous",
      unit: "mEq/L",
      coefficient: -0.012140915089,
      imputation: "prism_peleod_mid",
      derivationMedian: 25,
      step: 0.1,
      min: 0,
    },
    {
      id: "pelodwbc",
      label: "White blood cell count",
      group: "PELOD",
      type: "continuous",
      unit: "×10³/μL",
      coefficient: -0.027840645251,
      imputation: "prism_peleod_mid",
      derivationMedian: 7.5,
      step: 0.1,
      min: 0,
    },
    {
      id: "pelodplate",
      label: "Platelet count",
      group: "PELOD",
      type: "continuous",
      unit: "×10³/μL",
      coefficient: -0.0048082163746,
      imputation: "prism_peleod_mid",
      derivationMedian: 246.5,
      step: 1,
      min: 0,
    },
    {
      id: "pelodpt",
      label: "Prothrombin time",
      group: "PELOD",
      type: "continuous",
      unit: "sec",
      coefficient: 0.054725102557,
      imputation: "prism_peleod_mid",
      derivationMedian: 16.5,
      step: 0.1,
      min: 0,
    },
    {
      id: "pelodhr",
      label: "Heart rate",
      group: "PELOD",
      type: "continuous",
      unit: "bpm",
      coefficient: 0.0042030301508,
      imputation: "prism_peleod_mid",
      derivationMedian: 144,
      step: 1,
      min: 0,
    },
    {
      id: "pelodlact",
      label: "Lactate",
      group: "PELOD",
      type: "continuous",
      unit: "mmol/L",
      coefficient: 0.12834415842,
      imputation: "prism_peleod_mid",
      derivationMedian: 2.38,
      step: 0.1,
      min: 0,
    },
    {
      id: "vaso",
      label: "Vasopressor use",
      group: "Clinical characteristics",
      type: "binary",
      coefficient: 0.33205469147,
      imputation: "prism_peleod_mid",
      derivationMedian: 0,
      yesLabel: "Yes",
      noLabel: "No",
    },
    {
      id: "prisminpt",
      label: "Inpatient admission",
      group: "Clinical characteristics",
      type: "binary",
      coefficient: 0.28495875631,
      imputation: "prism_peleod_mid",
      derivationMedian: 0,
      yesLabel: "Yes",
      noLabel: "No",
    },
    {
      id: "prismpostop",
      label: "Postoperative admission",
      group: "Clinical characteristics",
      type: "binary",
      coefficient: -0.61202648001,
      imputation: "prism_peleod_mid",
      derivationMedian: 0,
      yesLabel: "Yes",
      noLabel: "No",
    },
    {
      id: "prismprevadm",
      label: "Previous ICU admission",
      group: "Clinical characteristics",
      type: "binary",
      coefficient: 0.13918431314,
      imputation: "prism_peleod_mid",
      derivationMedian: 0,
      yesLabel: "Yes",
      noLabel: "No",
    },
    {
      id: "prismcancer",
      label: "Underlying malignancy",
      group: "Clinical characteristics",
      type: "binary",
      coefficient: 0.68078964664,
      imputation: "prism_peleod_mid",
      derivationMedian: 0,
      yesLabel: "Yes",
      noLabel: "No",
    },
    {
      id: "wt",
      label: "Weight",
      group: "Demographics",
      type: "continuous",
      unit: "kg",
      coefficient: 0.0012136332675,
      imputation: "derivation_median",
      derivationMedian: 19.5,
      step: 0.1,
      min: 0,
    },
    {
      id: "male",
      label: "Male sex",
      group: "Demographics",
      type: "binary",
      coefficient: 0.27471142545,
      imputation: "prism_peleod_mid",
      derivationMedian: 0,
      yesLabel: "Male",
      noLabel: "Female / other",
    },
  ],
};
