/**
 * Validated test cases for the 19-feature HYPER-SCREEN model.
 * expected_probability values computed from the R validation pipeline.
 */
export const TEST_CASES = [
  {
    id: "tp_high_confidence",
    label: "TP — high-confidence hyper (~99.99%)",
    category: "complete",
    description: "True hyper correctly screened in with severe acidosis and cytopenias.",
    expected_probability: 0.9999,
    expected_result: "Hyperinflammatory",
    true_label: "Hyperinflammatory",
    inputs: {
      pelodwbc: { value: 5.6, missing: false },
      pelodplate: { value: 20, missing: false },
      pelodpt: { value: 125, missing: false },
      pelodhr: { value: 184, missing: false },
      pelodlact: { value: 2, missing: false },
      prismpao2lo: { value: 22, missing: false },
      prismbunhi: { value: 17, missing: false },
      prismph: { value: 6.88, missing: false },
      prismtemphi: { value: 38.5, missing: false },
      prismgluc: { value: 431, missing: false },
      intub: { value: 1, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 1, missing: false },
      vaso: { value: 1, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 1, missing: false },
      prismnonop: { value: 0, missing: false },
    },
  },
  {
    id: "tp_borderline_above",
    label: "TP — borderline hyper just above 0.70 (~70.06%)",
    category: "complete",
    description: "True hyper barely above the screening threshold.",
    expected_probability: 0.7006,
    expected_result: "Hyperinflammatory",
    true_label: "Hyperinflammatory",
    inputs: {
      pelodwbc: { value: 1.8, missing: false },
      pelodplate: { value: 31, missing: false },
      pelodpt: { value: 16.1, missing: false },
      pelodhr: { value: 98, missing: false },
      pelodlact: { value: 4.4, missing: false },
      prismpao2lo: { value: 36, missing: false },
      prismbunhi: { value: 7, missing: false },
      prismph: { value: 7.22, missing: false },
      prismtemphi: { value: 37, missing: false },
      prismgluc: { value: 407, missing: false },
      intub: { value: 1, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 1, missing: false },
      vaso: { value: 0, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 1, missing: false },
      prismnonop: { value: 0, missing: false },
    },
  },
  {
    id: "tn_clear_hypo",
    label: "TN — clear hypo (~5.68%)",
    category: "complete",
    description: "True hypo with normal-appearing inflammatory profile.",
    expected_probability: 0.0568,
    expected_result: "Hypoinflammatory",
    true_label: "Hypoinflammatory",
    inputs: {
      pelodwbc: { value: 22.26, missing: false },
      pelodplate: { value: 806, missing: false },
      pelodpt: { value: 16.1, missing: false },
      pelodhr: { value: 148, missing: false },
      pelodlact: { value: 3.94, missing: false },
      prismpao2lo: { value: 63.2, missing: false },
      prismbunhi: { value: 6, missing: false },
      prismph: { value: 7.32, missing: false },
      prismtemphi: { value: 37.1, missing: false },
      prismgluc: { value: 127, missing: false },
      intub: { value: 1, missing: false },
      wt: { value: 5.41, missing: false },
      male: { value: 1, missing: false },
      vaso: { value: 0, missing: false },
      prisminpt: { value: 1, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 0, missing: false },
      prismnonop: { value: 0, missing: false },
    },
  },
  {
    id: "tn_borderline_below",
    label: "TN — borderline hypo just below 0.70 (~69.95%)",
    category: "complete",
    description: "True hypo just under the screening threshold.",
    expected_probability: 0.6995,
    expected_result: "Hypoinflammatory",
    true_label: "Hypoinflammatory",
    inputs: {
      pelodwbc: { value: 6.9, missing: false },
      pelodplate: { value: 80, missing: false },
      pelodpt: { value: 18.7, missing: false },
      pelodhr: { value: 98, missing: false },
      pelodlact: { value: 3.6, missing: false },
      prismpao2lo: { value: 60.6, missing: false },
      prismbunhi: { value: 20, missing: false },
      prismph: { value: 7.32, missing: false },
      prismtemphi: { value: 38.28, missing: false },
      prismgluc: { value: 190, missing: false },
      intub: { value: 1, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 1, missing: false },
      vaso: { value: 1, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 0, missing: false },
      prismnonop: { value: 0, missing: false },
    },
  },
  {
    id: "fn_missed_hyper",
    label: "FN — true hyper missed (~69.20%)",
    category: "complete",
    description: "True hyper classified hypo — just below threshold.",
    expected_probability: 0.692,
    expected_result: "Hypoinflammatory",
    true_label: "Hyperinflammatory",
    inputs: {
      pelodwbc: { value: 19.8, missing: false },
      pelodplate: { value: 267, missing: false },
      pelodpt: { value: 13.9, missing: false },
      pelodhr: { value: 170, missing: false },
      pelodlact: { value: 11, missing: false },
      prismpao2lo: { value: 34, missing: false },
      prismbunhi: { value: 15, missing: false },
      prismph: { value: 7.147, missing: false },
      prismtemphi: { value: 37.89, missing: false },
      prismgluc: { value: 457, missing: false },
      intub: { value: 1, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 1, missing: false },
      vaso: { value: 1, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 0, missing: false },
      prismnonop: { value: 0, missing: false },
    },
  },
  {
    id: "fp_false_screen_in",
    label: "FP — false screen-in (~70.05%)",
    category: "complete",
    description: "True hypo classified hyper — just above threshold.",
    expected_probability: 0.7005,
    expected_result: "Hyperinflammatory",
    true_label: "Hypoinflammatory",
    inputs: {
      pelodwbc: { value: 2, missing: false },
      pelodplate: { value: 135, missing: false },
      pelodpt: { value: 11.9, missing: false },
      pelodhr: { value: 97, missing: false },
      pelodlact: { value: 5.3, missing: false },
      prismpao2lo: { value: 57, missing: false },
      prismbunhi: { value: 14, missing: false },
      prismph: { value: 7.411, missing: false },
      prismtemphi: { value: 38.28, missing: false },
      prismgluc: { value: 238, missing: false },
      intub: { value: 1, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 1, missing: false },
      vaso: { value: 1, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 1, missing: false },
      prismnonop: { value: 0, missing: false },
    },
  },
  {
    id: "missing_hyper_screened_in",
    label: "Missing — hyper still screened in (~99.99%)",
    category: "missing",
    description: "True hyper with 8 missing fields; imputation does not change screen-in.",
    expected_probability: 0.9999,
    expected_result: "Hyperinflammatory",
    true_label: "Hyperinflammatory",
    inputs: {
      pelodwbc: { value: 5.6, missing: false },
      pelodplate: { value: 20, missing: false },
      pelodpt: { value: 125, missing: false },
      pelodhr: { value: 184, missing: false },
      pelodlact: { missing: true },
      prismpao2lo: { value: 22, missing: false },
      prismbunhi: { value: 17, missing: false },
      prismph: { value: 6.88, missing: false },
      prismtemphi: { value: 38.5, missing: false },
      prismgluc: { value: 431, missing: false },
      intub: { missing: true },
      wt: { missing: true },
      male: { missing: true },
      vaso: { value: 1, missing: false },
      prisminpt: { missing: true },
      prismpostop: { missing: true },
      prismprevadm: { missing: true },
      prismcancer: { value: 1, missing: false },
      prismnonop: { missing: true },
    },
  },
  {
    id: "missing_clear_hypo",
    label: "Missing — clear hypo (~5.68%)",
    category: "missing",
    description: "True hypo with 6 missing fields; remains hypo after imputation.",
    expected_probability: 0.0568,
    expected_result: "Hypoinflammatory",
    true_label: "Hypoinflammatory",
    inputs: {
      pelodwbc: { value: 22.26, missing: false },
      pelodplate: { value: 806, missing: false },
      pelodpt: { missing: true },
      pelodhr: { missing: true },
      pelodlact: { value: 3.94, missing: false },
      prismpao2lo: { missing: true },
      prismbunhi: { value: 6, missing: false },
      prismph: { missing: true },
      prismtemphi: { value: 37.1, missing: false },
      prismgluc: { value: 127, missing: false },
      intub: { missing: true },
      wt: { value: 5.41, missing: false },
      male: { missing: true },
      vaso: { value: 0, missing: false },
      prisminpt: { value: 1, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 0, missing: false },
      prismnonop: { value: 0, missing: false },
    },
  },
  {
    id: "missing_borderline",
    label: "Missing — borderline hypo (~69.95%)",
    category: "missing",
    description: "Borderline true hypo with 7 support/demographic fields missing.",
    expected_probability: 0.6995,
    expected_result: "Hypoinflammatory",
    true_label: "Hypoinflammatory",
    inputs: {
      pelodwbc: { value: 6.9, missing: false },
      pelodplate: { value: 80, missing: false },
      pelodpt: { value: 18.7, missing: false },
      pelodhr: { value: 98, missing: false },
      pelodlact: { value: 3.6, missing: false },
      prismpao2lo: { value: 60.6, missing: false },
      prismbunhi: { value: 20, missing: false },
      prismph: { value: 7.32, missing: false },
      prismtemphi: { value: 38.28, missing: false },
      prismgluc: { value: 190, missing: false },
      intub: { missing: true },
      wt: { missing: true },
      male: { missing: true },
      vaso: { value: 1, missing: false },
      prisminpt: { missing: true },
      prismpostop: { missing: true },
      prismprevadm: { missing: true },
      prismcancer: { value: 0, missing: false },
      prismnonop: { missing: true },
    },
  },
  {
    id: "missing_mostly_imputed",
    label: "Missing — mostly imputed, acidotic (~88.44%)",
    category: "missing",
    description: "Only pH, lactate, sex, pressors, and ventilation provided.",
    expected_probability: 0.8844,
    expected_result: "Hyperinflammatory",
    true_label: "N/A",
    inputs: {
      pelodwbc: { missing: true },
      pelodplate: { missing: true },
      pelodpt: { missing: true },
      pelodhr: { missing: true },
      pelodlact: { value: 8, missing: false },
      prismpao2lo: { missing: true },
      prismbunhi: { missing: true },
      prismph: { value: 6.9, missing: false },
      prismtemphi: { missing: true },
      prismgluc: { missing: true },
      intub: { value: 1, missing: false },
      wt: { missing: true },
      male: { value: 1, missing: false },
      vaso: { value: 1, missing: false },
      prisminpt: { missing: true },
      prismpostop: { missing: true },
      prismprevadm: { missing: true },
      prismcancer: { missing: true },
      prismnonop: { missing: true },
    },
  },
];
