/**
 * JS-validated test cases — regenerate via:
 *   node scripts/generate-extra-test-cases.mjs
 */
export const TEST_CASES = [
  {
    id: "val_hyper_1",
    label: "Validation hyper (complete)",
    category: "complete",
    expected_probability: 0.9645,
    expected_calibrated_probability: 0.9162,
    expected_result: "Hyperinflammatory",
    ageyrs: 5.6925188744,
    inputs: {
      pelodwbc: { value: 0.3, missing: false },
      pelodplate: { value: 83, missing: false },
      pelodpt: { value: 17, missing: false },
      pelodhr: { value: 176, missing: false },
      pelodlact: { value: 5.8, missing: false },
      prismpao2lo: { value: 39, missing: false },
      prismbunhi: { value: 27, missing: false },
      prismph: { value: 7.165, missing: false },
      prismk: { value: 3.3, missing: false },
      prismtemphi: { value: 40.2777777778, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 0, missing: false },
      vaso: { value: 1, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 1, missing: false },
      prismnonop: { value: 0, missing: false },
      bicarb: { value: 23, missing: false },
    },
  },
  {
    id: "val_hypo_1",
    label: "Validation hypo (complete)",
    category: "complete",
    expected_probability: 0.5825,
    expected_calibrated_probability: 0.2099,
    expected_result: "Hypoinflammatory",
    ageyrs: 5.6925188744,
    inputs: {
      pelodwbc: { value: 6.6, missing: false },
      pelodplate: { value: 58, missing: false },
      pelodpt: { value: 16.5, missing: false },
      pelodhr: { value: 98, missing: false },
      pelodlact: { value: 0.8, missing: false },
      prismpao2lo: { value: 94.1, missing: false },
      prismbunhi: { value: 9, missing: false },
      prismph: { value: 7.319, missing: false },
      prismk: { value: 3.2, missing: false },
      prismtemphi: { value: 37.7777777778, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 0, missing: false },
      vaso: { value: 1, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 0, missing: false },
      prismnonop: { value: 0, missing: false },
      bicarb: { value: 25, missing: false },
    },
  },
  {
    id: "val_missing_lact_ph",
    label: "Validation hyper — lactate & pH imputed",
    category: "missing",
    expected_probability: 0.9502,
    expected_calibrated_probability: 0.8754,
    expected_result: "Hyperinflammatory",
    ageyrs: 5.6925188744,
    inputs: {
      pelodwbc: { value: 1.4, missing: false },
      pelodplate: { value: 7, missing: false },
      pelodpt: { value: 17.5, missing: false },
      pelodhr: { value: 196, missing: false },
      pelodlact: { missing: true },
      prismpao2lo: { value: 33, missing: false },
      prismbunhi: { value: 33, missing: false },
      prismph: { missing: true },
      prismk: { value: 3.6, missing: false },
      prismtemphi: { value: 38.2222222222, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 0, missing: false },
      vaso: { value: 1, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 1, missing: false },
      prismnonop: { value: 0, missing: false },
      bicarb: { value: 20, missing: false },
    },
  },
  {
    id: "val_hyper_2",
    label: "High-score example #1 (score 0.70)",
    category: "complete",
    expected_probability: 0.7008,
    expected_calibrated_probability: 0.337,
    expected_result: "Hyperinflammatory",
    ageyrs: 5.7,
    inputs: {
      pelodwbc: { value: 3.1, missing: false },
      pelodplate: { value: 49, missing: false },
      pelodpt: { value: 16.5, missing: false },
      pelodhr: { value: 94, missing: false },
      pelodlact: { value: 3, missing: false },
      prismpao2lo: { value: 24, missing: false },
      prismbunhi: { value: 19, missing: false },
      prismph: { value: 7.196, missing: false },
      prismk: { value: 4.2, missing: false },
      prismtemphi: { value: 37.5, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 0, missing: false },
      vaso: { value: 0, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 0, missing: false },
      prismnonop: { value: 0, missing: false },
      bicarb: { value: 21, missing: false },
    },
  },
  {
    id: "val_hyper_3",
    label: "High-score example #2 (score 0.79)",
    category: "complete",
    expected_probability: 0.7854,
    expected_calibrated_probability: 0.4706,
    expected_result: "Hyperinflammatory",
    ageyrs: 5.7,
    inputs: {
      pelodwbc: { value: 17.7, missing: false },
      pelodplate: { value: 123, missing: false },
      pelodpt: { value: 16.5, missing: false },
      pelodhr: { value: 168, missing: false },
      pelodlact: { value: 6.7, missing: false },
      prismpao2lo: { value: 38, missing: false },
      prismbunhi: { value: 20, missing: false },
      prismph: { value: 7.17, missing: false },
      prismk: { value: 5.7, missing: false },
      prismtemphi: { value: 38.3888888888889, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 0, missing: false },
      vaso: { value: 1, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 0, missing: false },
      prismnonop: { value: 0, missing: false },
      bicarb: { value: 17, missing: false },
    },
  },
  {
    id: "val_hyper_4",
    label: "High-score example #3 (score 0.87)",
    category: "complete",
    expected_probability: 0.8738,
    expected_calibrated_probability: 0.6636,
    expected_result: "Hyperinflammatory",
    ageyrs: 5.7,
    inputs: {
      pelodwbc: { value: 5.9, missing: false },
      pelodplate: { value: 66, missing: false },
      pelodpt: { value: 14.1, missing: false },
      pelodhr: { value: 97, missing: false },
      pelodlact: { value: 2.6, missing: false },
      prismpao2lo: { value: 43, missing: false },
      prismbunhi: { value: 28, missing: false },
      prismph: { value: 7.226, missing: false },
      prismk: { value: 5.8, missing: false },
      prismtemphi: { value: 39.2777777777778, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 0, missing: false },
      vaso: { value: 1, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 1, missing: false },
      prismnonop: { value: 0, missing: false },
      bicarb: { value: 23, missing: false },
    },
  },
  {
    id: "val_hyper_5",
    label: "High-score example #4 (score 0.96)",
    category: "complete",
    expected_probability: 0.9578,
    expected_calibrated_probability: 0.8971,
    expected_result: "Hyperinflammatory",
    ageyrs: 5.7,
    inputs: {
      pelodwbc: { value: 0.9, missing: false },
      pelodplate: { value: 22, missing: false },
      pelodpt: { value: 16.5, missing: false },
      pelodhr: { value: 183, missing: false },
      pelodlact: { value: 9.5, missing: false },
      prismpao2lo: { value: 39, missing: false },
      prismbunhi: { value: 14, missing: false },
      prismph: { value: 7.141, missing: false },
      prismk: { value: 3.4, missing: false },
      prismtemphi: { value: 37.3888888888889, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 0, missing: false },
      vaso: { value: 1, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 1, missing: false },
      prismnonop: { value: 0, missing: false },
      bicarb: { value: 21, missing: false },
    },
  },
  {
    id: "val_hyper_6",
    label: "High-score example #5 (score 1.00)",
    category: "complete",
    expected_probability: 0.9998,
    expected_calibrated_probability: 0.9999,
    expected_result: "Hyperinflammatory",
    ageyrs: 5.7,
    inputs: {
      pelodwbc: { value: 5.6, missing: false },
      pelodplate: { value: 20, missing: false },
      pelodpt: { value: 125, missing: false },
      pelodhr: { value: 184, missing: false },
      pelodlact: { value: 2.38, missing: false },
      prismpao2lo: { value: 22, missing: false },
      prismbunhi: { value: 17, missing: false },
      prismph: { value: 6.88, missing: false },
      prismk: { value: 5.1, missing: false },
      prismtemphi: { value: 38.5, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 0, missing: false },
      vaso: { value: 1, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 1, missing: false },
      prismnonop: { value: 0, missing: false },
      bicarb: { value: 9, missing: false },
    },
  },
  {
    id: "val_hypo_2",
    label: "Low-score example #1 (score 0.06)",
    category: "complete",
    expected_probability: 0.0589,
    expected_calibrated_probability: 0.0054,
    expected_result: "Hypoinflammatory",
    ageyrs: 5.7,
    inputs: {
      pelodwbc: { value: 16.9, missing: false },
      pelodplate: { value: 614, missing: false },
      pelodpt: { value: 16.5, missing: false },
      pelodhr: { value: 90, missing: false },
      pelodlact: { value: 4.2, missing: false },
      prismpao2lo: { value: 71.2, missing: false },
      prismbunhi: { value: 9, missing: false },
      prismph: { value: 7.338, missing: false },
      prismk: { value: 4.5, missing: false },
      prismtemphi: { value: 36.6111111111111, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 0, missing: false },
      vaso: { value: 0, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 0, missing: false },
      prismnonop: { value: 0, missing: false },
      bicarb: { value: 17, missing: false },
    },
  },
  {
    id: "val_hypo_3",
    label: "Low-score example #2 (score 0.32)",
    category: "complete",
    expected_probability: 0.3173,
    expected_calibrated_probability: 0.0629,
    expected_result: "Hypoinflammatory",
    ageyrs: 0.9966049721,
    inputs: {
      pelodwbc: { value: 7.5, missing: false },
      pelodplate: { value: 275.5, missing: false },
      pelodpt: { value: 16.5, missing: false },
      pelodhr: { value: 157, missing: false },
      pelodlact: { value: 2.38, missing: false },
      prismpao2lo: { value: 85, missing: false },
      prismbunhi: { value: 7, missing: false },
      prismph: { value: 7.375, missing: false },
      prismk: { value: 4.7, missing: false },
      prismtemphi: { value: 38.2, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 0, missing: false },
      vaso: { value: 0, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 0, missing: false },
      prismnonop: { value: 0, missing: false },
      bicarb: { value: 21.3, missing: false },
    },
  },
  {
    id: "val_hypo_4",
    label: "Low-score example #3 (score 0.47)",
    category: "complete",
    expected_probability: 0.4675,
    expected_calibrated_probability: 0.1296,
    expected_result: "Hypoinflammatory",
    ageyrs: 5.7,
    inputs: {
      pelodwbc: { value: 5.6, missing: false },
      pelodplate: { value: 194, missing: false },
      pelodpt: { value: 15.1, missing: false },
      pelodhr: { value: 96, missing: false },
      pelodlact: { value: 3.3, missing: false },
      prismpao2lo: { value: 91.1, missing: false },
      prismbunhi: { value: 17, missing: false },
      prismph: { value: 7.357, missing: false },
      prismk: { value: 3.5, missing: false },
      prismtemphi: { value: 37.6111111111111, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 0, missing: false },
      vaso: { value: 0, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 0, missing: false },
      prismnonop: { value: 0, missing: false },
      bicarb: { value: 21, missing: false },
    },
  },
  {
    id: "val_hypo_5",
    label: "Low-score example #4 (score 0.58)",
    category: "complete",
    expected_probability: 0.5803,
    expected_calibrated_probability: 0.2081,
    expected_result: "Hypoinflammatory",
    ageyrs: 5.6757200745,
    inputs: {
      pelodwbc: { value: 7.5, missing: false },
      pelodplate: { value: 275.5, missing: false },
      pelodpt: { value: 16.5, missing: false },
      pelodhr: { value: 137, missing: false },
      pelodlact: { value: 0.8, missing: false },
      prismpao2lo: { value: 85, missing: false },
      prismbunhi: { value: 19, missing: false },
      prismph: { value: 7.31, missing: false },
      prismk: { value: 3.8, missing: false },
      prismtemphi: { value: 37.1, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 0, missing: false },
      vaso: { value: 1, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 1, missing: false },
      prismnonop: { value: 0, missing: false },
      bicarb: { value: 25, missing: false },
    },
  },
  {
    id: "val_hypo_6",
    label: "Low-score example #5 (score 0.70)",
    category: "complete",
    expected_probability: 0.6967,
    expected_calibrated_probability: 0.3316,
    expected_result: "Hypoinflammatory",
    ageyrs: 5.7,
    inputs: {
      pelodwbc: { value: 17.5, missing: false },
      pelodplate: { value: 177, missing: false },
      pelodpt: { value: 16.5, missing: false },
      pelodhr: { value: 94, missing: false },
      pelodlact: { value: 9.9, missing: false },
      prismpao2lo: { value: 38, missing: false },
      prismbunhi: { value: 7, missing: false },
      prismph: { value: 7.093, missing: false },
      prismk: { value: 4.8, missing: false },
      prismtemphi: { value: 38.6111111111111, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 0, missing: false },
      vaso: { value: 1, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 0, missing: false },
      prismnonop: { value: 0, missing: false },
      bicarb: { value: 19, missing: false },
    },
  },
  {
    id: "val_borderline_1",
    label: "Near threshold (score 0.70)",
    category: "complete",
    expected_probability: 0.7008,
    expected_calibrated_probability: 0.337,
    expected_result: "Hyperinflammatory",
    ageyrs: 5.7,
    inputs: {
      pelodwbc: { value: 3.1, missing: false },
      pelodplate: { value: 49, missing: false },
      pelodpt: { value: 16.5, missing: false },
      pelodhr: { value: 94, missing: false },
      pelodlact: { value: 3, missing: false },
      prismpao2lo: { value: 24, missing: false },
      prismbunhi: { value: 19, missing: false },
      prismph: { value: 7.196, missing: false },
      prismk: { value: 4.2, missing: false },
      prismtemphi: { value: 37.5, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 0, missing: false },
      vaso: { value: 0, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 0, missing: false },
      prismnonop: { value: 0, missing: false },
      bicarb: { value: 21, missing: false },
    },
  },
  {
    id: "val_borderline_2",
    label: "Near threshold (score 0.70)",
    category: "complete",
    expected_probability: 0.7021,
    expected_calibrated_probability: 0.3387,
    expected_result: "Hyperinflammatory",
    ageyrs: 5.7,
    inputs: {
      pelodwbc: { value: 7.5, missing: false },
      pelodplate: { value: 275.5, missing: false },
      pelodpt: { value: 16.5, missing: false },
      pelodhr: { value: 224, missing: false },
      pelodlact: { value: 2, missing: false },
      prismpao2lo: { value: 37, missing: false },
      prismbunhi: { value: 9.95, missing: false },
      prismph: { value: 7.196, missing: false },
      prismk: { value: 2.1, missing: false },
      prismtemphi: { value: 41.7777777777778, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 0, missing: false },
      vaso: { value: 1, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 0, missing: false },
      prismnonop: { value: 0, missing: false },
      bicarb: { value: 26, missing: false },
    },
  },
  {
    id: "val_borderline_3",
    label: "Near threshold (score 0.70)",
    category: "complete",
    expected_probability: 0.6967,
    expected_calibrated_probability: 0.3316,
    expected_result: "Hypoinflammatory",
    ageyrs: 5.7,
    inputs: {
      pelodwbc: { value: 17.5, missing: false },
      pelodplate: { value: 177, missing: false },
      pelodpt: { value: 16.5, missing: false },
      pelodhr: { value: 94, missing: false },
      pelodlact: { value: 9.9, missing: false },
      prismpao2lo: { value: 38, missing: false },
      prismbunhi: { value: 7, missing: false },
      prismph: { value: 7.093, missing: false },
      prismk: { value: 4.8, missing: false },
      prismtemphi: { value: 38.6111111111111, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 0, missing: false },
      vaso: { value: 1, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 0, missing: false },
      prismnonop: { value: 0, missing: false },
      bicarb: { value: 19, missing: false },
    },
  },
  {
    id: "val_infant",
    label: "Infant example",
    category: "complete",
    expected_probability: 0.4772,
    expected_calibrated_probability: 0.1352,
    expected_result: "Hypoinflammatory",
    ageyrs: 0.3997371591,
    inputs: {
      pelodwbc: { value: 7.4, missing: false },
      pelodplate: { value: 228, missing: false },
      pelodpt: { value: 16.5, missing: false },
      pelodhr: { value: 157, missing: false },
      pelodlact: { value: 2.38, missing: false },
      prismpao2lo: { value: 85, missing: false },
      prismbunhi: { value: 9.95, missing: false },
      prismph: { value: 7.375, missing: false },
      prismk: { value: 5.2, missing: false },
      prismtemphi: { value: 37.2, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 1, missing: false },
      vaso: { value: 1, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 0, missing: false },
      prismnonop: { value: 0, missing: false },
      bicarb: { value: 23, missing: false },
    },
  },
  {
    id: "val_adolescent",
    label: "Adolescent example",
    category: "complete",
    expected_probability: 0.2909,
    expected_calibrated_probability: 0.0543,
    expected_result: "Hypoinflammatory",
    ageyrs: 14.61504764,
    inputs: {
      pelodwbc: { value: 3.5, missing: false },
      pelodplate: { value: 239, missing: false },
      pelodpt: { value: 16.5, missing: false },
      pelodhr: { value: 107, missing: false },
      pelodlact: { value: 2.38, missing: false },
      prismpao2lo: { value: 85, missing: false },
      prismbunhi: { value: 9.95, missing: false },
      prismph: { value: 7.375, missing: false },
      prismk: { value: 5.2, missing: false },
      prismtemphi: { value: 36.6, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 0, missing: false },
      vaso: { value: 0, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 0, missing: false },
      prismnonop: { value: 0, missing: false },
      bicarb: { value: 22.1, missing: false },
    },
  },
  {
    id: "val_missing_wt",
    label: "Hyper — weight imputed",
    category: "missing",
    expected_probability: 0.9998,
    expected_calibrated_probability: 0.9999,
    expected_result: "Hyperinflammatory",
    ageyrs: 5.7,
    inputs: {
      pelodwbc: { value: 5.6, missing: false },
      pelodplate: { value: 20, missing: false },
      pelodpt: { value: 125, missing: false },
      pelodhr: { value: 184, missing: false },
      pelodlact: { value: 2.38, missing: false },
      prismpao2lo: { value: 22, missing: false },
      prismbunhi: { value: 17, missing: false },
      prismph: { value: 6.88, missing: false },
      prismk: { value: 5.1, missing: false },
      prismtemphi: { value: 38.5, missing: false },
      wt: { missing: true },
      male: { value: 0, missing: false },
      vaso: { value: 1, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 1, missing: false },
      prismnonop: { value: 0, missing: false },
      bicarb: { value: 9, missing: false },
    },
  },
  {
    id: "val_missing_labs_cluster",
    label: "Hyper — WBC, platelets, BUN imputed",
    category: "missing",
    expected_probability: 0.2339,
    expected_calibrated_probability: 0.0382,
    expected_result: "Hypoinflammatory",
    ageyrs: 5.7,
    inputs: {
      pelodwbc: { missing: true },
      pelodplate: { missing: true },
      pelodpt: { value: 13.8, missing: false },
      pelodhr: { value: 96, missing: false },
      pelodlact: { value: 1, missing: false },
      prismpao2lo: { value: 40, missing: false },
      prismbunhi: { missing: true },
      prismph: { value: 7.217, missing: false },
      prismk: { value: 5.2, missing: false },
      prismtemphi: { value: 37.3888888888889, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 0, missing: false },
      vaso: { value: 0, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 0, missing: false },
      prismnonop: { value: 0, missing: false },
      bicarb: { value: 20, missing: false },
    },
  },
  {
    id: "val_missing_vitals",
    label: "Hyper — HR & temp imputed",
    category: "missing",
    expected_probability: 0.9989,
    expected_calibrated_probability: 0.9988,
    expected_result: "Hyperinflammatory",
    ageyrs: 5.7,
    inputs: {
      pelodwbc: { value: 7.9, missing: false },
      pelodplate: { value: 63, missing: false },
      pelodpt: { value: 36.7, missing: false },
      pelodhr: { missing: true },
      pelodlact: { value: 15.3, missing: false },
      prismpao2lo: { value: 32, missing: false },
      prismbunhi: { value: 105, missing: false },
      prismph: { value: 7.107, missing: false },
      prismk: { value: 6.3, missing: false },
      prismtemphi: { missing: true },
      wt: { value: 19.5, missing: false },
      male: { value: 0, missing: false },
      vaso: { value: 1, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 0, missing: false },
      prismnonop: { value: 0, missing: false },
      bicarb: { value: 15, missing: false },
    },
  },
  {
    id: "val_missing_gas",
    label: "Hyper — PaO₂ & bicarb imputed",
    category: "missing",
    expected_probability: 0.9977,
    expected_calibrated_probability: 0.9971,
    expected_result: "Hyperinflammatory",
    ageyrs: 5.7,
    inputs: {
      pelodwbc: { value: 18, missing: false },
      pelodplate: { value: 275, missing: false },
      pelodpt: { value: 125, missing: false },
      pelodhr: { value: 96, missing: false },
      pelodlact: { value: 12, missing: false },
      prismpao2lo: { missing: true },
      prismbunhi: { value: 20, missing: false },
      prismph: { value: 7.232, missing: false },
      prismk: { value: 8, missing: false },
      prismtemphi: { value: 36.8888888888889, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 0, missing: false },
      vaso: { value: 1, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 0, missing: false },
      prismnonop: { value: 0, missing: false },
      bicarb: { missing: true },
    },
  },
  {
    id: "val_missing_hypo_lact",
    label: "Hypo — lactate imputed",
    category: "missing",
    expected_probability: 0.0477,
    expected_calibrated_probability: 0.0041,
    expected_result: "Hypoinflammatory",
    ageyrs: 5.7,
    inputs: {
      pelodwbc: { value: 16.9, missing: false },
      pelodplate: { value: 614, missing: false },
      pelodpt: { value: 16.5, missing: false },
      pelodhr: { value: 90, missing: false },
      pelodlact: { missing: true },
      prismpao2lo: { value: 71.2, missing: false },
      prismbunhi: { value: 9, missing: false },
      prismph: { value: 7.338, missing: false },
      prismk: { value: 4.5, missing: false },
      prismtemphi: { value: 36.6111111111111, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 0, missing: false },
      vaso: { value: 0, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 0, missing: false },
      prismnonop: { value: 0, missing: false },
      bicarb: { value: 17, missing: false },
    },
  },
  {
    id: "val_missing_hypo_many",
    label: "Hypo — lactate, PT, potassium imputed",
    category: "missing",
    expected_probability: 0.0661,
    expected_calibrated_probability: 0.0063,
    expected_result: "Hypoinflammatory",
    ageyrs: 5.7,
    inputs: {
      pelodwbc: { value: 26.6, missing: false },
      pelodplate: { value: 595, missing: false },
      pelodpt: { missing: true },
      pelodhr: { value: 150, missing: false },
      pelodlact: { missing: true },
      prismpao2lo: { value: 52, missing: false },
      prismbunhi: { value: 9.95, missing: false },
      prismph: { value: 7.22, missing: false },
      prismk: { missing: true },
      prismtemphi: { value: 38.7222222222222, missing: false },
      wt: { value: 19.5, missing: false },
      male: { value: 0, missing: false },
      vaso: { value: 0, missing: false },
      prisminpt: { value: 0, missing: false },
      prismpostop: { value: 0, missing: false },
      prismprevadm: { value: 0, missing: false },
      prismcancer: { value: 0, missing: false },
      prismnonop: { value: 0, missing: false },
      bicarb: { value: 34, missing: false },
    },
  }
];
